version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - mynetwork

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin@localhost
      - MYSQL_DATABASE=assignment
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@localhost

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mariadb_data:
